/** Labels for saved TRACE B calculator keys (read-only report display). */

const ENTRIES: [string, string][] = [
  ["d1a_faculty", "D1a · Faculty"],
  ["d1b_school", "D1b · School"],
  ["d1c_centre", "D1c · Centre (or None)"],
  ["d1d_year", "D1d · Year of study"],
  ["d1e_mode", "D1e · Full-time or part-time"],
  ["d1f_setting", "D1f · Primary research setting"],
  ["f1a_primary_funding", "F1a · Primary PhD funding source"],
  ["f1b_additional", "F1b · Additional funding sources?"],
  ["f1c_additional_detail", "F1c · If yes, what type?"],
  ["l1a_papers", "L1a · Peer-reviewed papers (past 12 months)"],
  ["l1b_journals", "L1b · Journal names"],
  ["s1a_wfh", "S1a · Work from home regularly?"],
  ["s1b_wfh_days", "S1b · Days per week at home"],
  ["s2a_qub", "S2a · QUB site regularly?"],
  ["s2b_qub_days", "S2b · Days per week on QUB site"],
  ["s2c_main_building", "S2c · Main building"],
  ["s2d_main_hours", "S2d · Hours per week (main)"],
  ["s2e_sec_building", "S2e · Secondary building"],
  ["s2f_sec_hours", "S2f · Hours per week (secondary)"],
  ["s3a_share", "S3a · Share an office?"],
  ["s3b_share_count", "S3b · People you share with (band)"],
  ["s3c_lights", "S3c · Lights automatic or manual?"],
  ["s4a_other", "S4a · Other QUB spaces?"],
  ["s4b_other_detail", "S4b · Which spaces"],
  ["s4c_other_hours", "S4c · Hours per week in those spaces"],
  ["s5a_printer", "S5a · Use QUB printer on site?"],
  ["s5b_print_band", "S5b · Pages printed / day (band)"],
  ["s5c_copy_band", "S5c · Photocopy pages (band)"],
  ["s6a_kitchen", "S6a · Kitchen appliances on site?"],
  ["s6_kettle", "S6 · Kettle uses / day"],
  ["s6_micro", "S6 · Microwave uses / day"],
  ["s6_fridge", "S6 · Fridge uses / day"],
  ["s6_freezer", "S6 · Freezer uses / day"],
  ["s6_oven", "S6 · Oven uses / day"],
  ["s6_hot", "S6 · Hot water tap"],
  ["s6_cold", "S6 · Cold water tap"],
  ["s6_disp", "S6 · Water dispenser"],
  ["s7_bathroom", "S7a · Bathroom visits / day (band)"],
  ["t1a_primary", "T1a · Primary mode"],
  ["t1b_hours", "T1b · Hours per week (primary)"],
  ["t1c_km", "T1c · One-way distance"],
  ["t1d_sec", "T1d · Secondary mode"],
  ["t1e_hours", "T1e · Hours per week (secondary)"],
  ["t1f_km", "T1f · One-way distance (secondary)"],
  ["t2a_days", "T2a · Days per year (field / non-QUB sites)"],
  ["t2b_mode", "T2b · Primary mode"],
  ["t2c_time", "T2c · Time using primary mode"],
  ["t2d_km", "T2d · One-way distance"],
  ["t2e_sec", "T2e · Secondary mode"],
  ["t2f_time", "T2f · Secondary time"],
  ["t2g_km", "T2g · Secondary distance"],
  ["t3a_conf", "T3a · Conferences per year"],
  ["t3b_mode", "T3b · Primary mode"],
  ["t3c_time", "T3c · Time (primary)"],
  ["t3d_rt", "T3d · Round-trip distance (conference travel)"],
  ["t3e_sec", "T3e · Secondary mode"],
  ["t3f_time", "T3f · Secondary time"],
  ["t3g_km", "T3g · Secondary distance (one-way band)"],
  ["t3h_airline", "T3h · Airline (if flying)"],
  ["c1a_screen", "C1a · Project screen time / month (hours band)"],
  ["c1b_device", "C1b · Mostly PC, laptop or other?"],
  ["c1c_qub", "C1c · Device supplied by QUB?"],
  ["c1d_monitors", "C1d · Additional monitors"],
  ["c1e_mon_qub", "C1e · Monitors supplied by QUB?"],
  ["c1f_onedrive", "C1f · QUB OneDrive used (GB band)"],
  ["c1g_hdd", "C1g · Additional physical hard drive?"],
  ["c1h_hdd_gb", "C1h · HDD size (GB band)"],
  ["c1i_read", "C1i · % screen time: reading"],
  ["c1j_write", "C1j · % screen time: writing"],
  ["c1k_analysis", "C1k · % data analysis / specialist software"],
  ["c1l_meet", "C1l · % meetings / admin"],
  ["c2_hpc", "C2 · Use HPC / clusters?"],
  ["c2b_freq", "C2b · How often jobs run?"],
  ["c2c_jobs", "C2c · Job types (free text / multi)"],
  ["c2d_hours", "C2d · Hours per month on HPC"],
  ["c2e_gpu", "C2e · GPU use"],
  ["c3_cloud", "C3a · Cloud services (AWS/Azure/GCP)?"],
  ["c3b_freq", "C3b · Frequency"],
  ["c3c_data", "C3c · Research data volume"],
  ["c3d_where", "C3d · Where most research data is stored"],
  ["c7_ai", "C7a · Use AI tools for research?"],
  ["c7b_types", "C7b · Which types (multi / free text)"],
  ["c7_other", "C7 · Other AI tool (specify)"],
  ["c7c_freq", "C7c · Frequency"],
  ["c8_spec", "C8a · Specialist research equipment?"],
  ["c8b_types", "C8b · Types (multi / free text)"],
  ["c8c_freq", "C8c · How often"],
  ["c8d_hours", "C8d · Typical session length (hours)"],
  ["c8e_access", "C8e · How accessed"],
  ["r1_wet_lab", "R1 · Wet lab work as part of research?"],
  ["r1_animal", "R1 · Animal work?"],
  ["r1_field", "R1 · Field work?"],
  ["r2_other_equip_yn", "R2 · Other QUB specialist equipment?"],
  ["r2_other_equip_detail", "R2a · Specify equipment"],
  ["l1_sterilisation", "L1 · Sterilisation / autoclave / dishwasher"],
  ["l2_molecular", "L2 · Molecular biology"],
  ["l3_cell", "L3 · Cell biology & culture"],
  ["l4_microscopy", "L4 · Microscopy & imaging"],
  ["l5_xray", "L5 · X-Ray / CT microscopy hours"],
  ["l6_spectroscopy", "L6 · Spectroscopy / analytical chemistry"],
  ["l7_infrastructure", "L7 · Lab infrastructure (fume hoods, centrifuge…)"],
  ["l8a_cold", "L8A · Cold storage in use?"],
  ["l8b_size", "L8B · Size (m²)"],
  ["l8c_people", "L8C · People sharing"],
  ["l8d_power", "L8D · Power use (kWh/month band)"],
  ["l9a_plastic", "L9A · Plastic consumables (boxes/mo)"],
  ["l9b_plastic_supplier", "L9B · Supplier code"],
  ["l10a_glass", "L10A · Glass consumables (boxes/yr)"],
  ["l10b_glass_supplier", "L10B · Supplier code"],
  ["l11a_paper", "L11A · Paper consumables (boxes/yr)"],
  ["l11b_paper_supplier", "L11B · Supplier code"],
  ["l12a_chemical", "L12A · Chemical reagents (bottles/yr)"],
  ["l12b_chemical_supplier", "L12B · Supplier code"],
  ["l13a_molbio", "L13A · Molecular biology kits (kits/yr)"],
  ["l13b_molbio_supplier", "L13B · Supplier code"],
  ["l14a_enzyme", "L14A · Enzymes / biological reagents (vials/yr)"],
  ["l14b_enzyme_supplier", "L14B · Supplier code"],
  ["l15a_chroma", "L15A · Chromatography consumables (items/yr)"],
  ["l15b_chroma_supplier", "L15B · Supplier code"],
  ["l16a_cleaning", "L16A · Cleaning chemicals (L/yr)"],
  ["l16b_cleaning_supplier", "L16B · Supplier code"],
  ["l17a_sharps", "L17A · Medical sharps (boxes/yr)"],
  ["l17b_sharps_supplier", "L17B · Supplier code"],
  ["l18a_gas", "L18A · Industrial gas cylinders (cylinders/yr)"],
  ["l18b_gas_supplier", "L18B · Supplier code"],
  ["l19a_cryo", "L19A · Cryogenic supplies (L/yr)"],
  ["l19b_cryo_supplier", "L19B · Supplier code"],
  ["fld_studies", "F1 · Field studies this year (count)"],
  ["fld_multi", "F2 · Purchased multi-use field equipment?"],
  ["fld_items", "F3 · Equipment items"],
  ["fld_freq", "F4 · Use frequency"],
  ["fld_recharge", "F5 · Requires recharging?"],
  ["fld_battery", "F6 · Uses batteries?"],
  ["fld_bait", "F7 · Purchased bait?"],
  ["fld_bait_kg", "F7a · Bait amount (kg band)"],
  ["fld_bait_cat", "F7b · Bait category"],
  ["fld_bait_other", "F7c · Other bait detail"],
  ["an_studies", "A1 · Animal studies this year"],
  ["an_species", "A2 · Species"],
  ["an_count", "A2a · How many?"],
  ["an_class", "A2b · Organism class / size"],
  ["an_diet", "A2c · Diet"],
  ["an_external", "A2d · Hosted externally?"],
  ["an_feed", "A3 · Purchased feed?"],
  ["an_feed_kg", "A3a · Feed amount (kg band)"],
  ["an_feed_type", "A3b · Feed category"],
  ["an_feed_other", "A3c · Other feed"],
  ["or_paper", "R1 · Paper / paper-based resources?"],
  ["or_paper_types", "R1a · Types used (list)"],
  ["or_paper_amt", "R1b · Amount used (band)"],
  ["or_metal", "R2 · Metal resources?"],
  ["or_metal_kg", "R2a · Amount (kg band)"],
  ["or_metal_rec", "R2c · Recycled (kg band)"],
  ["or_wood", "R3 · Wood / wood-based?"],
  ["or_wood_kg", "R3a · Amount (kg band)"],
  ["or_wood_rec", "R3c · Recycled (kg band)"],
  ["or_plastic", "R4 · Plastic resources?"],
  ["or_plastic_kg", "R4a · Amount (kg band)"],
  ["or_plastic_rec", "R4c · Recycled (kg band)"],
  ["or_glass", "R5 · Glass resources?"],
  ["or_glass_kg", "R5a · Amount (kg band)"],
  ["or_glass_rec", "R5c · Recycled (kg band)"],
  ["or_other", "R6 · Other resources (describe)"],
  ["or_other_kg", "R6a · Amount (kg band)"],
  ["or_other_rec", "R6c · Recycled (kg band)"],
];

const HPC_MONTH_LABELS: [string, string][] = [
  ["jan", "January (kg CO₂e)"],
  ["feb", "February (kg CO₂e)"],
  ["mar", "March (kg CO₂e)"],
  ["apr", "April (kg CO₂e)"],
  ["may", "May (kg CO₂e)"],
  ["jun", "June (kg CO₂e)"],
  ["jul", "July (kg CO₂e)"],
  ["aug", "August (kg CO₂e)"],
  ["sep", "September (kg CO₂e)"],
  ["oct", "October (kg CO₂e)"],
  ["nov", "November (kg CO₂e)"],
  ["dec", "December (kg CO₂e)"],
];

export const TEAM_B_FIELD_LABELS: Record<string, string> = Object.fromEntries([
  ...ENTRIES,
  ...HPC_MONTH_LABELS,
]);

export function teamBFieldLabel(key: string): string {
  return TEAM_B_FIELD_LABELS[key] ?? key.replace(/_/g, " ");
}
